name: Rust Release Build

on:
  release:
    types: [published]
    branches: [master]

jobs:
  build:
    name: Build and Upload Executable
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        profile: minimal

    - name: Build release
      run: cargo build --release

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/release/makedot
        asset_name: makedot-${{ github.run_number }}
        asset_content_type: application/octet-stream
